name: flutter_application_task8
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  flutter_inappwebview: ^6.0.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi_web: '>=0.1.0-dev.1'
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/